name: Verify
on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 17, 18 ]
    name: React ${{ matrix.node }} Verify
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Dependencies
        run: yarn
      - name: Custom React version
        run: |
          yarn lerna add react@${{ matrix.react }} --scope=react-complex-tree --scope=react-complex-tree-blueprintjs-renderers
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Storybook
        run: yarn build-storybook
