name: Verify
on: push

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: [ 16, 17, 18 ]
    name: React ${{ matrix.react }} Verify
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v3
      - name: Dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Custom React version
        run: |
          yarn add react@${{ matrix.react }} -D
          cd packages/core
          yarn add react@${{ matrix.react }} -D
          yarn build
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint
      - name: Storybook
        run: yarn build-storybook
